project:
  type: website
  output-dir: docs
  
website:
  title: "Joe Shaw"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - writing.qmd
      - talks.qmd
      - projects.qmd
      - publications.qmd
      - education.qmd
      - contact.qmd
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Joe Shaw"

format:
  html:
    theme: darkly
    toc: true

editor: source

